### ISSUE TITLE
Error: only absoloute urls are supported

### ISSUE THREAD

**Issue by 3Chris** [rdegges/okta-express-login-portal#1]
Hello,

i am testing your portal, but after successful login (reported by okta) i get the following error at the dashboard site:

only absolute urls are supported

Error: only absolute urls are supported
    at /home/ec2-user/login-portal/node_modules/node-fetch/index.js:54:10
    at new Fetch (/home/ec2-user/login-portal/node_modules/node-fetch/index.js:49:9)
    at Fetch (/home/ec2-user/login-portal/node_modules/node-fetch/index.js:37:10)
    at module.exports (/home/ec2-user/login-portal/node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
    at RequestExecutor.fetch (/home/ec2-user/login-portal/node_modules/@okta/okta-sdk-nodejs/src/request-executor.js:19:12)
    at cacheMiddleware (/home/ec2-user/login-portal/node_modules/@okta/okta-sdk-nodejs/src/http.js:72:30)
    at Promise.resolve.then (/home/ec2-user/login-portal/node_modules/@okta/okta-sdk-nodejs/src/default-cache-middleware.js:32:15)

The only difference between yours and mine is, that i am using an amazon cloud server and not localhost.

Thank you and best Regards,
Christian

**Comment by mizodo** [comment]
I was running into a similar error message.  Check two that your `redirect_uri` has the correct string listed and that your `redirect_uri` matches the one listed in the Okta application settings.  I originally had my authenticated route in the URI and this was messing it up, so I removed it and simply used  `${process.env.HOST_URL}/authorization-code/callback` instead.  Made sure this was the same in the app.js and Okta app settings and then it worked as expected.
